### ISSUE TITLE
Request to be a member of sealer

### ISSUE THREAD

**Issue by jsparter** [sealerio/community#6]
For some time in the past, I've been learning more and more from the community, and communicating with others more and more by coming up with problems and proposing my ways to fix them. I hope I can become a member of this rapidly developing community, learn and progress together with everyone, and make more contributions in the future

**Comment by justadogistaken** [comment]
@allencloud Could you please help add @jsparter as a member?

**Comment by justadogistaken** [comment]
Welcome!

**Comment by allencloud** [comment]
I have sent the invitation request to @jsparter . Please approve that.

And welcome, of course. 🌹

**Comment by jsparter** [comment]
Thank you all! I hope to learn more from the community, and make further progress together!
