### ISSUE TITLE
Request to be a member of sealer

### ISSUE THREAD

**Issue by zhy76** [sealerio/community#7]
I have been deeply attracted by the design of sealer since I got to know the project. Gradually, I began to participate in some work and discussions in the community. I found that the people in the community are very warm-hearted. In the process of participating in the community work, I have learned a lot and feel that I still have a lot to learn. Therefore, I hope to become a sealer member of this excellent community, learn more from the community, improve myself and make more contributions to the community!

**Comment by starnop** [comment]
You're more than welcome to join us! 👏 

And, of course, looking forward to your first big feature: building sealer's e2e test framework with container infra!

**Comment by starnop** [comment]
@allencloud  Could you please help add @zhy76 as a member?

**Comment by allencloud** [comment]
@zhy76 I have sent the invitation to you. After your permission, you will be in sealer org as a member and be a sealer reviewer. /cc @Starnop

**Comment by zhy76** [comment]
Thanks all, I think I can learn more in the community, and I hope I can do more valuable and meaningful things in the community!
